import { Analysis, RepositoryInfo } from '@shared/types';

/**
 * Export utilities for generating Markdown and PDF exports of analysis results
 */

/**
 * Format the analysis content with metadata header for export
 */
export function formatAnalysisForExport(analysis: Analysis, repoInfo: RepositoryInfo): string {
    const generatedDate = new Date(analysis.generatedAt).toLocaleString();
    const providerName = analysis.provider.charAt(0).toUpperCase() + analysis.provider.slice(1);

    const header = `# Repository Analysis Report

> **Repository:** [${repoInfo.owner}/${repoInfo.repo}](https://github.com/${repoInfo.owner}/${repoInfo.repo})  
> **Branch:** ${repoInfo.branch}  
> **Generated:** ${generatedDate}  
> **AI Provider:** ${providerName}  
> **Generated by:** [CodeMind](https://github.com/AhmedV20/codemind) - AI-Powered Repository Analyzer

---

`;

    return header + analysis.content;
}

/**
 * Export analysis as a Markdown file
 */
export function exportAsMarkdown(analysis: Analysis, repoInfo: RepositoryInfo): void {
    const content = formatAnalysisForExport(analysis, repoInfo);
    const filename = `${repoInfo.owner}-${repoInfo.repo}-analysis.md`;

    downloadFile(content, filename, 'text/markdown');
}

/**
 * Export analysis as a professional PDF document
 */
export async function exportAsPDF(analysis: Analysis, repoInfo: RepositoryInfo): Promise<void> {
    const { jsPDF } = await import('jspdf');

    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let yPosition = margin;

    // Colors
    const primaryColor: [number, number, number] = [139, 92, 246]; // Purple
    const textColor: [number, number, number] = [31, 41, 55]; // Dark gray
    const mutedColor: [number, number, number] = [107, 114, 128]; // Gray

    // Header with gradient-like background
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 45, 'F');

    // Logo/Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('CodeMind', margin, 20);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Repository Analysis Report', margin, 30);

    // Repository info in header
    doc.setFontSize(10);
    doc.text(`${repoInfo.owner}/${repoInfo.repo}`, margin, 38);

    yPosition = 55;

    // Metadata section
    doc.setTextColor(...mutedColor);
    doc.setFontSize(9);
    const generatedDate = new Date(analysis.generatedAt).toLocaleString();
    const providerName = analysis.provider.charAt(0).toUpperCase() + analysis.provider.slice(1);
    doc.text(`Generated: ${generatedDate}  |  AI Provider: ${providerName}  |  Branch: ${repoInfo.branch}`, margin, yPosition);

    yPosition += 10;

    // Divider line
    doc.setDrawColor(...primaryColor);
    doc.setLineWidth(0.5);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);

    yPosition += 10;

    // Parse and render content
    doc.setTextColor(...textColor);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    const content = analysis.content;
    const lines = content.split('\n');

    for (const line of lines) {
        // Check if we need a new page
        if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = margin;
        }

        const trimmedLine = line.trim();

        // Handle different markdown elements
        if (trimmedLine.startsWith('## ')) {
            // H2 - Section header
            yPosition += 5;
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...primaryColor);
            const headerText = trimmedLine.replace('## ', '').replace(/[🎯💡👤🛠️✨🚀📥📊💬📋]/g, '').trim();
            doc.text(headerText, margin, yPosition);
            yPosition += 8;
            doc.setTextColor(...textColor);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
        } else if (trimmedLine.startsWith('### ')) {
            // H3 - Subsection header
            yPosition += 3;
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            const headerText = trimmedLine.replace('### ', '').replace(/[📦⚙️📄📖]/g, '').trim();
            doc.text(headerText, margin, yPosition);
            yPosition += 6;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
        } else if (trimmedLine.startsWith('> ')) {
            // Blockquote
            doc.setFillColor(243, 244, 246);
            doc.rect(margin, yPosition - 4, contentWidth, 8, 'F');
            doc.setTextColor(...mutedColor);
            const quoteText = trimmedLine.replace('> ', '').replace(/\*\*/g, '');
            const splitQuote = doc.splitTextToSize(quoteText, contentWidth - 10);
            doc.text(splitQuote, margin + 5, yPosition);
            yPosition += (splitQuote.length * 5) + 3;
            doc.setTextColor(...textColor);
        } else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
            // List item
            const listText = trimmedLine.replace(/^[-*] /, '').replace(/\*\*/g, '');
            const splitList = doc.splitTextToSize(`• ${listText}`, contentWidth - 10);
            doc.text(splitList, margin + 5, yPosition);
            yPosition += (splitList.length * 5);
        } else if (trimmedLine.match(/^\d+\. /)) {
            // Numbered list
            const listText = trimmedLine.replace(/\*\*/g, '');
            const splitList = doc.splitTextToSize(listText, contentWidth - 5);
            doc.text(splitList, margin + 3, yPosition);
            yPosition += (splitList.length * 5);
        } else if (trimmedLine.startsWith('|')) {
            // Table - simplified handling
            const cells = trimmedLine.split('|').filter(c => c.trim() && !c.includes('---'));
            if (cells.length > 0) {
                const cellWidth = contentWidth / cells.length;
                cells.forEach((cell, i) => {
                    const cellText = cell.trim().replace(/\*\*/g, '');
                    doc.text(cellText.substring(0, 25), margin + (i * cellWidth), yPosition);
                });
                yPosition += 5;
            }
        } else if (trimmedLine.startsWith('```')) {
            // Code block - just skip the markers
            yPosition += 2;
        } else if (trimmedLine.length > 0 && !trimmedLine.startsWith('---')) {
            // Regular paragraph
            const cleanText = trimmedLine.replace(/\*\*/g, '').replace(/\*/g, '');
            const splitText = doc.splitTextToSize(cleanText, contentWidth);
            doc.text(splitText, margin, yPosition);
            yPosition += (splitText.length * 5);
        } else if (trimmedLine === '') {
            // Empty line
            yPosition += 3;
        }
    }

    // Footer on last page
    const footerY = pageHeight - 10;
    doc.setFontSize(8);
    doc.setTextColor(...mutedColor);
    doc.text(
        `Generated by CodeMind | https://github.com/AhmedV20/codemind`,
        pageWidth / 2,
        footerY,
        { align: 'center' }
    );

    // Save the PDF
    const filename = `${repoInfo.owner}-${repoInfo.repo}-analysis.pdf`;
    doc.save(filename);
}

/**
 * Helper function to download a file
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();

    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
